version: "3.8"

services:
  serverest:
    image: paulogoncalvesbh/serverest:latest
    ports:
      - "3000:3000"
    networks:
      - test-network

  tests:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run test:integration"
    depends_on:
      - serverest
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
