name: Run Integration Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: |
          chmod +x ./run-tests.sh
          ./run-tests.sh

      - name: Tear down Docker containers
        if: always()  # Ensures this runs even if the test fails
        run: docker-compose down
